---

- hosts: all
  tasks:
  - name: Ansible create new file with permissions example.
    become:yes
    file:
      path: "/home/ec2-user/shourya.txt"
      state: touch
      mode: 0644
      owner: ec2-user
