---
- hosts: this
  gather_facts: no
  tasks:
  - name: install epel
    yum:
      name: epel-release
      state: present
    become: yes
  - name: update 
    yum:
      name: yum 
      state: latest
    become: yes
  - name: install java
    yum:
      name: java-1.8.0-openjdk.x86_64 
      state: present
    become: yes
  - name: create directoy
    file:
      name: /opt/tomcat
      state: directory
    become: yes
  - name: groupadd tomcat
    group:
      name: tomcat
      state: present
    become: yes
  - name: useradd tomcat
    user:
      name: tomcat
      shell: /bin/nologin
      group: tomcat
      move_home: yes
      home: /opt/tomcat
    become: yes
  - name: download tomcat
    get_url:
      url: http://mirrors.wuchna.com/apachemirror/tomcat/tomcat-8/v8.5.35/bin/apache-tomcat-8.5.35.tar.gz
      dest: /home/ec2-user
  - name: unpack tomcat 
    unarchive:
      remote_src: yes 
      src: /home/ec2-user/apache-tomcat-8.5.35.tar.gz
      dest: /opt/tomcat/
      extra_opts: [--strip-components=1]
    become: yes
  - name: change permissions
    become: yes
    tags:
      - permissions
    file:
      path: /opt/tomcat/{{item}}
      owner: tomcat
      recurse: yes
      mode: "g+r"
    with_items:
      - conf
      - bin
    file:
      path: /opt/tomcat/{{item}}
      mode: "g+rwx"
    with_items:
      - conf
      - bin
    file:
      path: /opt/tomcat/{{item}} 
      recurse: yes
      owner: tomcat
    with_items:
      - temp
      - logs
      - webapps
      - work
    file:
       owner: tomcat
       recurse: yes
       path: /opt/tomcat/{{item}}
    with_items:
       - bin
       - lib
      
